Repository Kernel360/KFE3-e2e-Chwee-up-hajah, pull requests merged in 2025-07, with the labels that each got.

#97 Refactor/auction overlay, add api
  apps/web/app/(main)/auction/[auctionId]/auction-detail/page.tsx
  apps/web/app/api/auction/add/route.ts
  apps/web/features/auction/ui/AuctionOverlay.tsx
Labels: Refactor

#101 refactor: productSection 컴포넌트 api app route 방식으로 변경 (#100)
  apps/web/app/(main)/main/page.tsx
  apps/web/app/api/product/route.ts
  apps/web/features/product-list/model/fetchProductList.ts
  apps/web/features/product-list/ui/ProductList.tsx
  apps/web/hooks/product-list/useProductList.test.tsx
  apps/web/hooks/product-list/useProductList.ts
  apps/web/tsconfig.json
  apps/web/types/productsList.ts
Labels: Refactor

#103 Fix/avatar storage upload #89
  apps/web/app/api/profile/upload-avatar/route.ts
  apps/web/features/profile/api/updateProfile.ts
  apps/web/features/profile/api/uploadAvatar.ts
  apps/web/features/profile/model/handlers.ts
  apps/web/features/profile/ui/ProfileAvatarUpload.tsx
  apps/web/hooks/profile/useUpdateProfile.ts
  apps/web/lib/utils/avatar.ts
  apps/web/widgets/profile/ui/ProfileForm.tsx
  apps/web/widgets/profile/ui/UserProfileCard.tsx
Labels: Fix, Refactor

#106 feat: footer href 페이지 연결
  apps/web/app/(main)/profile/page.tsx
  apps/web/app/(main)/profile/update/page.tsx
  apps/web/widgets/footer/ui/Footer.tsx
Labels: Feat

#116 Fix/profile avatar hydration #110
  apps/web/features/profile/ui/ProfileAvatarUpload.tsx
  apps/web/widgets/profile/ui/ProfileForm.tsx
Labels: Fix

#113 refactor: chat 페이지 - css 스타일 상수화 (#99)
  apps/web/features/chat-list/ui/ChatRoomItem.tsx
  apps/web/features/chat-list/ui/ChatRoomList.tsx
  apps/web/features/chat-list/ui/styles/ChatRoomItem.styles.ts
  apps/web/features/chat-list/ui/styles/ChatRoomList.styles.ts
  apps/web/features/chat-room/ui/ChatInput.tsx
  apps/web/features/chat-room/ui/ChatMessages.tsx
  apps/web/features/chat-room/ui/styles/ChatInput.styles.ts
  apps/web/features/chat-room/ui/styles/ChatMessages.styles.ts
Labels: Refactor

#122 refactor: 모달 컴포넌트 타입 정의 분리(#120)
  apps/web/types/modal/index.ts
  apps/web/widgets/modal/ui/NotificationModal.tsx
Labels: Refactor

#135 Feat/profile error handling #131
  apps/web/app/session.ts
  apps/web/features/profile/api/getProfile.ts
  apps/web/features/profile/api/updateProfile.ts
  apps/web/features/profile/api/uploadAvatar.ts
Labels: Feat

#139 Refactor/separate component styles #119
  apps/web/features/profile/styles/profileAvatarUpload.styles.ts
  apps/web/features/profile/ui/ProfileAvatarUpload.tsx
  apps/web/widgets/footer/styles/footer.styles.ts
  apps/web/widgets/footer/ui/Footer.tsx
  apps/web/widgets/header/styles/header.styles.ts
  apps/web/widgets/header/ui/Header.tsx
  apps/web/widgets/modal/styles/locationModal.styles.ts
  apps/web/widgets/modal/styles/locationPermissionModal.ts
  apps/web/widgets/modal/styles/notificationModal.styles.ts
  apps/web/widgets/modal/ui/LocationModal.tsx
  apps/web/widgets/modal/ui/LocationPermissionModal.tsx
  apps/web/widgets/modal/ui/NotificationModal.tsx
  apps/web/widgets/profile/styles/chargeHistory.styles.ts
  apps/web/widgets/profile/styles/navigation.styles.ts
  apps/web/widgets/profile/styles/profileForm.styles.ts
  apps/web/widgets/profile/styles/useProfileCard.styles.ts
  apps/web/widgets/profile/ui/ChargeHistoryList.tsx
  apps/web/widgets/profile/ui/Navigation.tsx
  apps/web/widgets/profile/ui/ProfileForm.tsx
  apps/web/widgets/profile/ui/UserProfileCard.tsx
Labels: Refactor

#136 [refactor]: 경매 등록 페이지 구조 리펙토링
  apps/web/app/(main)/auction/auction-add/page.tsx
  apps/web/features/auction-add/model/useAuctionAddForm.ts
  apps/web/features/auction-add/ui/AuctionDateSelector.tsx
  apps/web/features/auction-add/ui/ErrorMessage.tsx
  packages/ui/src/utils/getToday.ts
Labels: Refactor

#148 refactor: main page 관련 컴포- css 상수화 (#147)
  apps/web/app/(main)/main/page.tsx
  apps/web/app/(main)/main/styles/main.styles.ts
  apps/web/features/product-list/ui/ProductCard.tsx
  apps/web/features/product-list/ui/ProductList.tsx
  apps/web/features/product-list/ui/styles/product-card.styles.ts
  apps/web/features/product-list/ui/styles/product-list.styles.ts
  apps/web/widgets/image-banner/ui/ImageBanner.tsx
  apps/web/widgets/image-banner/ui/styles/image-banner.styles.ts
  apps/web/widgets/product-section-header/ui/SectionHeader.tsx
  apps/web/widgets/product-section-header/ui/styles/section-header.styles.ts
  apps/web/widgets/product-section/ui/ProductSection.tsx
  apps/web/widgets/product-section/ui/styles/product-section.styles.ts
Labels: Refactor

#146 fix: 경매 상세 페이지 판매자 정보 누락된 avatar, score 값 받도록 api 수정
  apps/web/app/api/auction/detail/[auctionId]/route.ts
  apps/web/features/auction-add/ui/AuctionDateSelector.tsx
  apps/web/features/auction-add/ui/ErrorMessage.tsx
  apps/web/hooks/useCreateAuction.ts
  packages/ui/src/design-system/base-components/Card/Card.styles.ts
Labels: Fix

#151 feat: SectionHeader - 더보기 rotuer.push 추가 (#150)
  apps/web/app/(main)/main/page.tsx
Labels: Feat

#177 feat: chat e2e 테스트- 테스트 파일 생성 , 기존 테스트 파일 삭제(#174)
  apps/web/cypress/e2e/1-getting-started/todo.cy.js
  apps/web/cypress/e2e/2-advanced-examples/actions.cy.js
  apps/web/cypress/e2e/2-advanced-examples/aliasing.cy.js
  apps/web/cypress/e2e/2-advanced-examples/assertions.cy.js
  apps/web/cypress/e2e/2-advanced-examples/connectors.cy.js
  apps/web/cypress/e2e/2-advanced-examples/cookies.cy.js
  apps/web/cypress/e2e/2-advanced-examples/cypress_api.cy.js
  apps/web/cypress/e2e/2-advanced-examples/files.cy.js
  apps/web/cypress/e2e/2-advanced-examples/location.cy.js
  apps/web/cypress/e2e/2-advanced-examples/misc.cy.js
  apps/web/cypress/e2e/2-advanced-examples/navigation.cy.js
  apps/web/cypress/e2e/2-advanced-examples/network_requests.cy.js
  apps/web/cypress/e2e/2-advanced-examples/querying.cy.js
  apps/web/cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js
  apps/web/cypress/e2e/2-advanced-examples/storage.cy.js
  apps/web/cypress/e2e/2-advanced-examples/traversal.cy.js
  apps/web/cypress/e2e/2-advanced-examples/utilities.cy.js
  apps/web/cypress/e2e/2-advanced-examples/viewport.cy.js
  apps/web/cypress/e2e/2-advanced-examples/waiting.cy.js
  apps/web/cypress/e2e/2-advanced-examples/window.cy.js
  apps/web/cypress/e2e/chat/chat-room-detail.cy.ts
  apps/web/cypress/e2e/chat/chat-rooms.cy.ts
Labels: Feat

#182 Feat/my listings #156
  apps/web/app/(main)/auction/my-listings/page.tsx
  apps/web/app/api/auction/my-listings/ended/route.ts
  apps/web/app/api/auction/my-listings/in-progress/route.ts
  apps/web/app/api/auction/my-participated/route.ts
  apps/web/app/api/auction/my-won-auctions/route.ts
  apps/web/shared/api/client/auction/useMyListings.ts
  apps/web/widgets/my-listings/ui/MyListings.tsx
Labels: Feat

#184 fix: 프로필 업데이트 로직 재적용(유실된 코드 복구)
  apps/web/features/profile/ui/ProfileAvatarUpload.tsx
  apps/web/widgets/profile/ui/ProfileForm.tsx
Labels: Fix

#195 Feat/search #163
  apps/web/app/(main)/auction/auction-list/page.tsx
  apps/web/app/(main)/auction/my-listings/page.tsx
  apps/web/app/api/auction/list/route.ts
  apps/web/shared/api/client/auction/useAuctionList.ts
  apps/web/shared/api/server/auction/fetchAuctionList.ts
  apps/web/shared/types/auction/index.ts
  apps/web/widgets/footer/ui/Footer.tsx
  apps/web/widgets/search/index.ts
  apps/web/widgets/search/styles/searchInput.styles.ts
  apps/web/widgets/search/ui/SearchInput.tsx
Labels: Feat

#208 Refactor/search #201
  apps/web/app/api/auction/list/route.ts
  apps/web/app/api/auction/put/[auctionId]/route.ts
Labels: Refactor

#219 [feat] 경매 리스트 무한스크롤 적용 및 정렬 기준 변경
  apps/web/app/(main)/auction/auction-list/page.tsx
  apps/web/app/api/auction/list/route.ts
  apps/web/package.json
  apps/web/shared/api/client/auction/useAuctionList.ts
  apps/web/shared/api/server/auction/fetchAuctionList.ts
  apps/web/shared/lib/utils/mapAuctionItem.ts
  apps/web/widgets/auction-listings/ui/styles/AuctionListings.styles.ts
  pnpm-lock.yaml
Labels: Feat, Refactor

#220 feat: pwa- push 기능 구현 (#216)
  apps/web/app/api/chat/message-send/route.ts
  apps/web/app/api/push-subscribe/route.ts
  apps/web/app/global-error.tsx
  apps/web/app/layout.tsx
  apps/web/features/chat-room/model/subscribeToMessages.ts
  apps/web/features/chat-room/ui/ChatInput.tsx
  apps/web/features/test/NotificationPermissionButton.tsx
  apps/web/next.config.ts
  apps/web/package.json
  apps/web/public/sw.js
  apps/web/public/sw.js.map
  apps/web/shared/api/client/push/usePushSubscription.ts
  apps/web/shared/api/server/push/sendSubscriptionToServer.ts
  apps/web/shared/hooks/PushSubscriptionEffect.tsx
  apps/web/shared/lib/push/registerPushSubscription.ts
  apps/web/shared/lib/utils/urlBase64ToUint8Array.ts
  pnpm-lock.yaml
Labels: Feat

#223 [feat]: 경매 유찰 flow 구현
  apps/web/app/(main)/auction/[auctionId]/auction-detail/page.tsx
  apps/web/features/auction-add/model/useAuctionForm.ts
  apps/web/features/auction/ui/AuctionOverlay.tsx
  apps/web/features/auction/ui/styles/AuctionOverlay.ts
Labels: Feat

#234 Feat/auction alaram #76
  apps/web/app/(main)/cron-test/page.tsx
  apps/web/app/api/auction/bid/route.ts
  apps/web/app/api/cron/check-auctions/route.ts
  apps/web/features/auction/services/auctionNotificationService.ts
  apps/web/public/sw.js
  apps/web/public/sw.js.map
  apps/web/public/worker-fc6e7a474b0c5ba3.js
  apps/web/public/worker-fc6e7a474b0c5ba3.js.map
  apps/web/shared/lib/notification/sendNotification.ts
  apps/web/shared/lib/utils/parseUTCDate.ts
  apps/web/shared/types/db.ts
  apps/web/worker/index.js
Labels: Feat

#244 [fix]: realtime- 구독 생명주기가 원인 (#243)
  apps/web/features/chat-room/model/subscribeToMessages.ts
  apps/web/shared/stores/chatSubscriptionStore.ts
Labels: Fix

#252 [feat]: 핫딜 경매 페이지 마크업
  apps/web/app/(main)/hotdeal/[hotdealId]/detail/page.tsx
  apps/web/widgets/image-banner/ui/ImageBanner.tsx
  apps/web/widgets/progress-bar/index.tsx
  apps/web/widgets/progress-bar/ui/ProgressBar.tsx
  apps/web/widgets/scroll-button/ScrollButton.tsx
Labels: Feat

#265 [feat] 카테고리, 경매상세페이지 이동, 메인페이지 로직 추가 (#264)
  apps/web/app/(main)/main/page.tsx
  apps/web/app/api/product/route.ts
  apps/web/app/page.tsx
  apps/web/features/product-list/ui/ProductCard.tsx
  apps/web/shared/api/client/product/useProductList.ts
  apps/web/shared/types/product/index.ts
  apps/web/widgets/product-section/styles/product-section.styles.ts
  apps/web/widgets/product-section/types/index.ts
  apps/web/widgets/product-section/ui/ProductSection.tsx
  packages/ui/src/design-system/base-components/Category/Category.tsx
Labels: Feat

#271 [feat] 핫딜 경매 로직 생성
  apps/web/app/(main)/hotdeal/[hotdealId]/detail/page.tsx
  apps/web/app/api/hotdeal/[hotdealId]/detail/route.ts
  apps/web/app/api/hotdeal/purchase/route.ts
  apps/web/features/hotdeal/model/useCountdown.ts
  apps/web/features/hotdeal/model/useHotdealCountdownLogic.ts
  apps/web/features/hotdeal/model/useHotdealRealtime.ts
  apps/web/shared/api/client/hotdeal/useHotdealDetail.ts
  apps/web/shared/api/client/hotdeal/usePurchaseHotdeal.ts
  apps/web/shared/api/server/hotdeal/fetchHotdealDetail.ts
  apps/web/shared/api/server/hotdeal/postPurchaseHotdeal.ts
  apps/web/shared/types/db.ts
  apps/web/widgets/hotdeal-info-card/index.ts
  apps/web/widgets/hotdeal-info-card/ui/HotdealInfoCard.tsx
  apps/web/widgets/loading-spiner/index.ts
  apps/web/widgets/loading-spiner/ui/LodingSpinner.tsx
Labels: Feat

#299 refactor: 참여 중 경매 중 같은 경매면 내 최고 입찰가만 남기기
  apps/web/app/api/auction/my-participated/route.ts
Labels: Refactor

#306 [style]: 경매 관련 페이지 미비된 스타일 개선
  apps/web/features/auction-add/ui/styles/AuctionDateSelector.styles.ts
  apps/web/features/auction-add/ui/styles/AuctionImageUploader.styles.ts
  apps/web/features/auction-add/ui/styles/ProductDescriptionInput.styles.ts
  apps/web/features/auction/ui/AuctionCardBase.tsx
  apps/web/features/auction/ui/styles/AuctionCard.styles.ts
  apps/web/widgets/auction-form/ui/AuctionForm.tsx
  packages/ui/src/design-system/base-components/Select/Select.styles.ts
Labels: Style

#321 Refactor/point #318
  apps/web/app/api/point/deduct-test/route.ts
  apps/web/widgets/profile/ui/PointsHistoryList.tsx
  apps/web/widgets/profile/ui/PointsTestButton.tsx
  apps/web/widgets/profile/ui/UserProfileCard.tsx
Labels: Refactor

#327 [refactor]: 경매 관련 피드백 적용 및 토스트 적용
  apps/web/app/(main)/auction/[auctionId]/auction-detail/page.tsx
  apps/web/app/(main)/auction/auction-list/page.tsx
  apps/web/app/(main)/hotdeal/[hotdealId]/detail/page.tsx
  apps/web/app/api/auction/bid/route.ts
  apps/web/app/api/auction/detail/[auctionId]/route.ts
  apps/web/app/layout.tsx
  apps/web/features/auction-add/model/handlers.ts
  apps/web/features/auction-add/model/useAuctionForm.ts
  apps/web/features/auction-detail/model/useAuctionBidState.ts
  apps/web/features/auction-detail/model/useBidCostHandlers.ts
  apps/web/features/auction-detail/model/useSendBid.ts
  apps/web/features/auction/ui/AuctionCardBase.tsx
  apps/web/shared/api/client/auction/useAuctionBid.ts
  apps/web/shared/api/client/auction/useAuctionDetail.ts
  apps/web/shared/api/client/auction/useAuctionImage.ts
  apps/web/shared/api/client/auction/useAuctionList.ts
  apps/web/shared/api/client/auction/useCreateAuction.ts
  apps/web/shared/api/client/auction/useDeleteAuction.ts
  apps/web/shared/api/client/auction/useMyListings.ts
  apps/web/shared/api/client/auction/useMyParticipatedAuctions.ts
  apps/web/shared/api/client/auction/useUpdateAuction.ts
  apps/web/shared/api/client/hotdeal/usePurchaseHotdeal.ts
  apps/web/shared/api/server/auction/postAuctionBid.ts
  apps/web/shared/lib/utils/auctionStatus.ts
  apps/web/shared/types/auction/index.ts
  apps/web/shared/types/db.ts
  apps/web/widgets/auction-detail-card/ui/AuctionDetailCard.tsx
  apps/web/widgets/auction-detail-card/ui/AuctionSellerProfile.tsx
  apps/web/widgets/auction-detail-card/ui/styles/AuctionDetailCard.styles.ts
  apps/web/widgets/auction-listings/ui/AuctionListings.tsx
  apps/web/widgets/my-listings/ui/MyListings.tsx
  apps/web/widgets/my-participated/ui/MyParticipatedAuctions.tsx
  packages/ui/src/utils/getTimeLeftString.ts
Labels: Refactor

#330 [Fix] 프로필 auction status 수정 및 toast 적용
  apps/web/app/(main)/auction/my-listings/page.tsx
  apps/web/app/(main)/profile/page.tsx
  apps/web/app/(no-footer)/layout.tsx
  apps/web/app/api/auction/list/route.ts
  apps/web/app/api/auction/my-listings/closed/route.ts
  apps/web/app/api/auction/my-listings/in-progress/route.ts
  apps/web/app/api/auction/my-participated/route.ts
  apps/web/app/api/auction/my-won-auctions/route.ts
  apps/web/shared/api/client/profile/useUpdateProfile.ts
  apps/web/widgets/authentication/LogoutButton.tsx
  apps/web/widgets/profile/ui/PointsTestButton.tsx
Labels: Fix

#332 [refactor]: 경매 등록, 수정 form 피드백 적용
  apps/web/app/(main)/auction/[auctionId]/auction-detail/page.tsx
  apps/web/app/(no-footer)/auction/[auctionId]/auction-edit/page.tsx
  apps/web/app/api/auction/add/route.ts
  apps/web/app/api/auction/put/[auctionId]/route.ts
  apps/web/features/auction-add/model/handlers.ts
  apps/web/features/auction-add/model/useAuctionForm.ts
  apps/web/features/auction-add/ui/styles/ErrorMessage.styles.ts
  apps/web/features/auction-detail/model/useAuctionBidState.ts
  apps/web/shared/lib/validators/auctionAddSchema.ts
  apps/web/shared/types/db.ts
  apps/web/widgets/auction-form/ui/AuctionForm.tsx
Labels: Refactor

#339 [style]: 경매 리스트 스타일 변경
  apps/web/app/(main)/auction/auction-list/page.tsx
  apps/web/app/(main)/auction/my-listings/page.tsx
  apps/web/app/(main)/auction/my-participated/page.tsx
  apps/web/app/(main)/auction/my-won-auctions/page.tsx
  apps/web/features/auction/ui/AuctionCardBase.tsx
  apps/web/features/auction/ui/AuctionCardContent.tsx
  apps/web/features/auction/ui/AuctionListItem.tsx
  apps/web/features/auction/ui/AuctionOverlay.tsx
  apps/web/features/auction/ui/styles/AuctionCard.styles.ts
  apps/web/features/auction/ui/styles/AuctionListItem.styles.ts
  apps/web/shared/lib/utils/mapAuctionItem.ts
  apps/web/shared/types/auction/index.ts
  apps/web/widgets/auction-listings/ui/AuctionListings.tsx
  apps/web/widgets/auction-listings/ui/styles/AuctionListings.styles.ts
  apps/web/widgets/footer/styles/footer.styles.ts
  apps/web/widgets/my-listings/ui/MyListings.tsx
  apps/web/widgets/my-participated/ui/MyParticipatedAuctions.tsx
  apps/web/widgets/my-won-auctions/ui/MyWonAuctions.tsx
  apps/web/widgets/scroll-button/ScrollButton.styles.ts
Labels: Style, Refactor

#340 feat: confirm dialog 컴포넌트 생성 & 위치 알림 삭제
  apps/web/features/auction-add/model/useAuctionForm.ts
  apps/web/shared/stores/modal.ts
  apps/web/widgets/auction-detail-card/ui/AuctionDetailCard.tsx
  apps/web/widgets/authentication/LogoutButton.tsx
  apps/web/widgets/authentication/styles/index.ts
  apps/web/widgets/modal/index.ts
  apps/web/widgets/modal/styles/confirmDialog.ts
  apps/web/widgets/modal/ui/ConfirmDialog.tsx
  apps/web/widgets/modal/ui/LocationModal.tsx
  apps/web/widgets/modal/ui/LocationPermissionModal.tsx
  apps/web/widgets/modal/ui/ModalProvider.tsx
Labels: Style, Refactor

#341 [refactor] 전반적인 main UI 수정, 카테고리 UI 수정
  apps/web/app/(main)/main/page.tsx
  apps/web/app/(main)/main/styles/main.styles.ts
  apps/web/app/api/product/route.ts
  apps/web/app/layout.tsx
  apps/web/features/product-list/ui/ProductCard.tsx
  apps/web/features/product-list/ui/ProductList.tsx
  apps/web/features/product-list/ui/styles/product-card.styles.ts
  apps/web/features/product-list/ui/styles/product-list.styles.ts
  apps/web/package.json
  apps/web/public/TA.png
  apps/web/public/TA.webp
  apps/web/public/exbanner1.png
  apps/web/public/exbanner2.png
  apps/web/shared/api/client/product/useProductList.ts
  apps/web/shared/api/client/push/usePushSubscription.ts
  apps/web/shared/api/server/product/fetchProductList.ts
  apps/web/shared/hooks/PushSubscriptionEffect.tsx
  apps/web/shared/lib/notification/sendNotification.ts
  apps/web/shared/lib/push/registerPushSubscription.ts
  apps/web/shared/lib/utils/time.ts
  apps/web/shared/mock/auction.ts
  apps/web/shared/types/product/index.ts
  apps/web/widgets/banner-bg/ui/BannerBackGround.tsx
  apps/web/widgets/events/eventPopup.tsx
  apps/web/widgets/header/ui/Header.tsx
  apps/web/widgets/image-banner/ui/EventBanner.tsx
  apps/web/widgets/product-section-header/ui/SectionHeader.tsx
  apps/web/widgets/product-section-header/ui/styles/section-header.styles.ts
  apps/web/widgets/product-section/styles/product-section.styles.ts
  apps/web/widgets/product-section/types/index.ts
  apps/web/widgets/product-section/ui/ProductSection.tsx
  packages/ui/src/design-system/base-components/Category/Category.Styles.ts
  packages/ui/src/design-system/base-components/Category/Category.tsx
  pnpm-lock.yaml
Labels: Refactor
