Repository Kernel360/KFE3-e2e-Chwee-up-hajah, pull requests merged in 2025-08, with the labels that each got.

#359 Refactor/icon #320
  apps/web/features/auction-add/ui/AuctionImageUploader.tsx
  apps/web/features/auction-add/ui/styles/AuctionImageUploader.styles.ts
  apps/web/features/auction/ui/AuctionOverlay.tsx
  apps/web/features/chat-room/ui/ChatRoomHeader.tsx
  apps/web/features/profile/ui/ProfileAvatarUpload.tsx
  apps/web/package.json
  apps/web/widgets/auction-detail-card/ui/AuctionDetailCard.tsx
  apps/web/widgets/authentication/LogoutButton.tsx
  apps/web/widgets/footer/ui/Footer.tsx
  apps/web/widgets/header/styles/header.styles.ts
  apps/web/widgets/header/ui/Header.tsx
  apps/web/widgets/modal/styles/notificationModal.styles.ts
  apps/web/widgets/modal/ui/NotificationModal.tsx
  apps/web/widgets/profile/styles/pointsHistory.styles.ts
  apps/web/widgets/profile/styles/useProfileCard.styles.ts
  apps/web/widgets/profile/ui/Navigation.tsx
  apps/web/widgets/profile/ui/PointsHistoryList.tsx
  apps/web/widgets/profile/ui/UserProfileCard.tsx
  apps/web/widgets/scroll-button/ScrollButton.styles.ts
  apps/web/widgets/scroll-button/ScrollButton.tsx
  apps/web/widgets/search/ui/SearchInput.tsx
  packages/ui/package.json
  packages/ui/src/design-system/base-components/CustomCheckbox/CustomCheckbox.tsx
  packages/ui/src/design-system/base-components/Input/Input.tsx
  packages/ui/src/design-system/base-components/LocationInfo/LocationInfo.styles.ts
  packages/ui/src/design-system/base-components/LocationInfo/LocationInfo.tsx
  packages/ui/src/design-system/base-components/Modal/Modal.tsx
  pnpm-lock.yaml
Labels: Style, Refactor

#368 fix: 사용자가 구독한 모든 디바이스에 푸시 알림
  apps/web/shared/lib/notification/sendNotification.ts
  apps/web/shared/types/notification/index.ts
Labels: Fix

#375 [fix] 핫딜 멀티 디바이스 알림 적용
  apps/web/app/(auth)/signup/page.tsx
  apps/web/shared/lib/notification/pushService.ts
  apps/web/widgets/authentication/styles/index.ts
  apps/web/widgets/header/ui/Header.tsx
  apps/web/widgets/modal/ui/NotificationModal.tsx
Labels: Fix

#376 [Fix] chat에 push 오류 #290
  apps/web/app/api/chat/confirm-completion/route.ts
  apps/web/app/api/chat/message-send/route.ts
  apps/web/app/api/chat/reject-completion/route.ts
  apps/web/app/api/chat/request-completion/route.ts
  apps/web/widgets/modal/ui/NotificationModalItem.tsx
Labels: Fix

#378 [refactor]: 경매 이미지 최적화, 경매 등록 관련 로직 수정 및 전체 로딩스피너 적용
  apps/web/app/(main)/auction/[auctionId]/auction-detail/page.tsx
  apps/web/app/(main)/auction/auction-list/page.tsx
  apps/web/app/(main)/auction/my-listings/page.tsx
  apps/web/app/(main)/auction/my-participated/page.tsx
  apps/web/app/(main)/auction/my-won-auctions/page.tsx
  apps/web/app/(main)/hotdeal/[hotdealId]/detail/page.tsx
  apps/web/app/(no-footer)/chat/[roomId]/page.tsx
  apps/web/app/(test)/admin/hot_deals/page.tsx
  apps/web/features/auction-add/model/handlers.ts
  apps/web/features/auction-add/model/useAuctionForm.ts
  apps/web/features/auction-add/ui/AuctionImageUploader.tsx
  apps/web/features/auction-detail/model/useAuctionBidState.ts
  apps/web/widgets/auction-form/ui/AuctionForm.tsx
  apps/web/widgets/hotdeal-info-card/ui/HotdealInfoCard.tsx
  apps/web/widgets/image-banner/ui/ImageBanner.tsx
  apps/web/widgets/image-banner/ui/styles/image-banner.styles.ts
  packages/ui/src/design-system/base-components/Button/Button.tsx
  packages/ui/src/utils/getTimeLeftString.ts
Labels: Refactor

#392 Fix/svg unoptimize #391
  apps/web/app/(main)/hotdeal/[hotdealId]/detail/page.tsx
  apps/web/app/(main)/layout.tsx
  apps/web/widgets/scroll-button/ScrollButton.styles.ts
  packages/ui/src/design-system/base-components/Avatar/Avatar.tsx
Labels: Fix, Style
