Repository Kernel360/KFE3-e2e-Chwee-up-hajah, pull requests merged in 2025-06, with the labels that each got.

#15 chore: xstate 설치 및 예제 파일 생성
  apps/docs/machines/machines-example.ts
  apps/docs/package.json
  pnpm-lock.yaml
Labels: Chore

#22 Fix/tailwindconfig #19
  .vscode/settings.json
  apps/docs/.storybook/preview.ts
  apps/docs/app/globals.css
  apps/docs/app/layout.tsx
  apps/docs/next.config.ts
  apps/docs/stories/global-styles.css
  packages/tailwind-config/package.json
  packages/ui/package.json
  packages/ui/src/design-system/base-components/Badge/Badge.tsx
  packages/ui/src/global.css
  packages/ui/src/styles.css
  packages/ui/src/theme.css
Labels: Fix

#30 Fix/css import structure #29
  apps/docs/app/globals.css
  apps/web/app/globals.css
  apps/web/app/page.tsx
  packages/ui/src/design-system/base-components/Badge/Badge.tsx
Labels: Refactor

#36 Feat/auction card #24
  apps/docs/stories/Card.stories.tsx
  apps/web/entities/auction/ui/AuctionCard.tsx
  packages/ui/src/design-system/base-components/Card/Card.tsx
  packages/ui/src/utils/formatNumberWithComma.ts
  packages/ui/src/utils/getTimeLeftString.ts
Labels: Feat, Refactor

#38 Feat/profile #4
  apps/web/app/(main)/auction/my-listings/page.tsx
  apps/web/app/(main)/auction/participating/page.tsx
  apps/web/app/(main)/auction/won-items/page.tsx
  apps/web/app/(main)/profile/charge-history/page.tsx
  apps/web/app/(main)/profile/page.tsx
  apps/web/entities/auction/ui/AuctionCard.tsx
  apps/web/pages/charge-history-page/index.ts
  apps/web/pages/charge-history-page/ui/index.tsx
  apps/web/pages/my-listings-page/index.ts
  apps/web/pages/my-listings-page/ui/index.tsx
  apps/web/pages/profile-page/index.ts
  apps/web/pages/profile-page/ui/index.tsx
  apps/web/widgets/auction-listings/index.ts
  apps/web/widgets/auction-listings/ui/AuctionListings.tsx
  apps/web/widgets/profile/index.ts
  apps/web/widgets/profile/types/index.ts
  apps/web/widgets/profile/ui/ChargeHistoryList.tsx
  apps/web/widgets/profile/ui/Navigation.tsx
  apps/web/widgets/profile/ui/UserProfileCard.tsx
Labels: Feat

#47 feat: 경매 등록 페이지 제작
  apps/web/app/(main)/auction/auction-add/page.tsx
  apps/web/entities/auction/ui/AuctionDateSelector.tsx
  apps/web/entities/auction/ui/ProductDescriptionInput.tsx
  apps/web/pages/auction-add-page/index.ts
  apps/web/pages/auction-add-page/ui/Select.tsx
  apps/web/pages/auction-add-page/ui/index.tsx
  apps/web/pages/auction-list-page/ui/index.tsx
  apps/web/widgets/profile/ui/UserProfileCard.tsx
  packages/ui/src/design-system/base-components/Card/Card.tsx
  packages/ui/src/design-system/base-components/LocationInfo/LocationInfo.tsx
  packages/ui/src/design-system/base-components/LocationInfo/index.ts
  packages/ui/src/design-system/base-components/Select/Select.tsx
  packages/ui/src/design-system/base-components/Select/index.ts
Labels: Feat

#62 Feat/alarm #42
  apps/web/app/(main)/layout.tsx
  apps/web/stores/modal.ts
  apps/web/widgets/header/ui/Header.tsx
  apps/web/widgets/modal/index.ts
  apps/web/widgets/modal/ui/LocationModal.tsx
  apps/web/widgets/modal/ui/LocationPermissionModal.tsx
  apps/web/widgets/modal/ui/NotificationModal.tsx
  apps/web/widgets/profile/ui/ChargeHistoryList.tsx
  packages/ui/src/design-system/base-components/Item/Item.tsx
  packages/ui/src/design-system/base-components/Item/index.ts
  packages/ui/src/design-system/base-components/Modal/Modal.tsx
  packages/ui/src/design-system/base-components/Modal/index.ts
Labels: Feat

#80 [feat] : 경매 상세 페이지 로직 개발
  apps/web/app/(main)/auction/[auctionId]/auction-detail/page.tsx
  apps/web/app/api/auction/bid/route.ts
  apps/web/app/api/auction/bidder-name/route.ts
  apps/web/app/api/auction/detail/[auctionId]/route.ts
  apps/web/features/auction/ui/AuctionBidHistoryCard.tsx
  apps/web/hooks/useAuctionBid.ts
  apps/web/hooks/useAuctionDetail.ts
  apps/web/hooks/useCreateAuction.ts
  apps/web/hooks/useRealTimeBid.ts
  apps/web/types/db.ts
  apps/web/widgets/auction-detail-card/ui/AuctionDescriptionCard.tsx
  apps/web/widgets/auction-detail-card/ui/AuctionDetailCard.tsx
  apps/web/widgets/auction-detail-card/ui/AuctionSellerProfile.tsx
  apps/web/widgets/image-banner/ui/ImageBanner.tsx
  packages/ui/src/design-system/base-components/Card/Card.tsx
Labels: Feat

#83 [feat] : 경매 종료 관련 오버레이 작업
  apps/web/app/(main)/auction/[auctionId]/auction-detail/page.tsx
  apps/web/app/api/auction/detail/[auctionId]/route.ts
  apps/web/app/api/auction/list/route.ts
  apps/web/features/auction/ui/AuctionBidHistoryCard.tsx
  apps/web/features/auction/ui/AuctionCard.tsx
  apps/web/features/auction/ui/AuctionImageUploader.tsx
  apps/web/features/auction/ui/AuctionOverlay.tsx
  apps/web/widgets/auction-detail-card/ui/AuctionDescriptionCard.tsx
  apps/web/widgets/auction-detail-card/ui/AuctionDetailCard.tsx
  apps/web/widgets/auction-detail-card/ui/AuctionSellerProfile.tsx
  apps/web/widgets/auction-listings/ui/AuctionListings.tsx
Labels: Feat
